version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      node:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: /apps/desktop/src-tauri
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      rust:
        patterns:
          - '*'
