import { defineConfig } from 'oxfmt'
import { oxfmtConfig } from '@viclafouch/oxc-config/formatting'

export default defineConfig({
  ...oxfmtConfig,
  ignorePatterns: [
    '**/node_modules/**',
    'dist/**',
    // Rust side, formatted by rustfmt
    'src-tauri/**',
    'package-lock.json',
    // Generated by standard-version
    'CHANGELOG.md'
  ]
})
