import { defineConfig } from 'oxlint'
import {
  hooks,
  imports,
  jsxA11y,
  react,
  typescript,
  vitest
} from '@viclafouch/oxc-config'

/**
 * An override replaces the plugins it inherits instead of adding to them, so a
 * test file has to name them all.
 */
const TEST_PLUGINS = [
  ...typescript.plugins,
  ...react.plugins,
  ...hooks.plugins,
  ...jsxA11y.plugins,
  ...imports.plugins,
  ...vitest.plugins
]

export default defineConfig({
  extends: [typescript, react, hooks, jsxA11y, imports],
  ignorePatterns: [
    '**/node_modules/**',
    'dist/**',
    // Rust side, linted by clippy and formatted by rustfmt
    'src-tauri/**',
    // Release tooling, loaded by `standard-version` through `require`, so it
    // has to be CommonJS while the rest of the repository is ESM. That puts it
    // outside the TypeScript project, and the type-aware rules have nothing to
    // say about a file the project does not contain.
    'scripts/*.cjs'
  ],
  options: {
    typeAware: true,
    typeCheck: true
  },
  overrides: [
    {
      // The vitest plugin reads a test file, and `require-hook` calls the mount
      // of `main.tsx` a setup left outside a hook. Hence an override and not
      // `extends`, which would ask that rule of the whole interface.
      files: ['src/**/*.test.ts'],
      plugins: TEST_PLUGINS,
      rules: {
        ...vitest.rules,
        // A test lives next to the module it reads, and carries its name.
        'vitest/consistent-test-filename': [
          'error',
          { pattern: String.raw`.*\.test\.ts$` }
        ]
      }
    },
    {
      // Generated by the shadcn CLI, kept close to upstream so that
      // regenerating a component does not reintroduce lint errors.
      // `cn` also cannot satisfy prefer-readonly-parameter-types: clsx's
      // ClassValue is recursively mutable.
      files: ['src/components/ui/**', 'src/lib/utils.ts'],
      rules: {
        'typescript/prefer-readonly-parameter-types': 'off',
        'react/function-component-definition': 'off',
        'eslint/no-restricted-imports': 'off'
      }
    },
    {
      files: [
        'src/app.tsx',
        'src/components/**',
        'src/hooks/**',
        'src/screens/**'
      ],
      rules: {
        'typescript/prefer-readonly-parameter-types': 'off'
      }
    }
  ]
})
