import { defineConfig } from 'oxlint'
import {
  hooks,
  imports,
  jsxA11y,
  react,
  typescript
} from '@viclafouch/oxc-config'

export default defineConfig({
  extends: [typescript, react, hooks, jsxA11y, imports],
  ignorePatterns: [
    '**/node_modules/**',
    'dist/**',
    // Rust side, linted by clippy and formatted by rustfmt
    'src-tauri/**'
  ],
  options: {
    typeAware: true,
    typeCheck: true
  },
  overrides: [
    {
      // Generated by the shadcn CLI, kept close to upstream so that
      // regenerating a component does not reintroduce lint errors.
      // `cn` also cannot satisfy prefer-readonly-parameter-types: clsx's
      // ClassValue is recursively mutable.
      files: ['src/components/ui/**', 'src/lib/utils.ts'],
      rules: {
        'typescript/prefer-readonly-parameter-types': 'off',
        'react/function-component-definition': 'off',
        'eslint/no-restricted-imports': 'off'
      }
    },
    {
      files: [
        'src/app.tsx',
        'src/components/**',
        'src/hooks/**',
        'src/screens/**'
      ],
      rules: {
        'typescript/prefer-readonly-parameter-types': 'off'
      }
    }
  ]
})
