/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as R404RouteImport } from './routes/404'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnSlugRouteImport } from './routes/en/$slug'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as EsSlugRouteImport } from './routes/es/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSlugRoute = EnSlugRouteImport.update({
  id: '/en/$slug',
  path: '/en/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsSlugRoute = EsSlugRouteImport.update({
  id: '/es/$slug',
  path: '/es/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/robots.txt': typeof RobotsDottxtRoute
  '/en/$slug': typeof EnSlugRoute
  '/es/$slug': typeof EsSlugRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/robots.txt': typeof RobotsDottxtRoute
  '/en/$slug': typeof EnSlugRoute
  '/es/$slug': typeof EsSlugRoute
  '/en': typeof EnIndexRoute
  '/es': typeof EsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/robots.txt': typeof RobotsDottxtRoute
  '/en/$slug': typeof EnSlugRoute
  '/es/$slug': typeof EsSlugRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/404'
    | '/robots.txt'
    | '/en/$slug'
    | '/es/$slug'
    | '/en/'
    | '/es/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/404'
    | '/robots.txt'
    | '/en/$slug'
    | '/es/$slug'
    | '/en'
    | '/es'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/404'
    | '/robots.txt'
    | '/en/$slug'
    | '/es/$slug'
    | '/en/'
    | '/es/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  R404Route: typeof R404Route
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  EnSlugRoute: typeof EnSlugRoute
  EsSlugRoute: typeof EsSlugRoute
  EnIndexRoute: typeof EnIndexRoute
  EsIndexRoute: typeof EsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/$slug': {
      id: '/en/$slug'
      path: '/en/$slug'
      fullPath: '/en/$slug'
      preLoaderRoute: typeof EnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/$slug': {
      id: '/es/$slug'
      path: '/es/$slug'
      fullPath: '/es/$slug'
      preLoaderRoute: typeof EsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  R404Route: R404Route,
  RobotsDottxtRoute: RobotsDottxtRoute,
  EnSlugRoute: EnSlugRoute,
  EsSlugRoute: EsSlugRoute,
  EnIndexRoute: EnIndexRoute,
  EsIndexRoute: EsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
